version: '3'
services:
  nest-docker:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    platform: linux/amd64
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: npm run start:dev