name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest repo
        uses: actions/checkout@master
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Deploy Elastic Beanstalk application
        uses: aws-actions/aws-elasticbeanstalk-deploy@v1
        with:
          environment-name: nest-docker
          application-name: nest-docker
          version-label: ${{ github.sha }}
          wait-until-deployed: true