name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest repo
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.SOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: nest-docker/nest-docker:latest

      # - name: Build image
      #   run: docker build -t nest-docker -f ./Dockerfile
      # - name: Tag image
      #   run: docker tag nest-docker nest-docker:latest
      # - name: Push to dockerhub
      #   run: docker push nest-docker
      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v14
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
      #     application_name: nest-docker
      #     environment_name: nest-docker-dev
      #     version_label: "app-cbe0-210131_121135"
      #     region: us-east-1